name: 'Project Scan & Terraform Validate'

on: [pull_request]

jobs:
  terraform:
    name: Validate Terraform Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Stub SSH key
        run: |
          mkdir -p ~/.ssh
          echo "ssh-rsa dummy-key" > ~/.ssh/id_rsa.pub
          
      - name: Find and Validate Terraform Projects
        run: |
          for dir in $(find . -type f -name "*.tf" -exec dirname {} \; | sort -u); do
            echo "Validating $dir"
            cd "$dir"
            echo "Running 'terraform init -backend=false'"
            terraform init -backend=false
            echo "Running 'terraform fmt -check'"
            terraform fmt -check
            echo "Running 'terraform validate'"
            terraform validate
            echo "${dir} was Successuflly Validated"
            cd -
          done